blueprint:
  name: Schedule Heater - ON/OFF
  description: "This automation blueprint turn the heater OFF"
  domain: automation
  input:
    energy_sensor:
      name: Tibber Current Price
      selector:
        entity:
          integration: tibber
          domain: sensor
      default: ""
    accepted_percentage:
      name: Accepted Price (%)
      description: Price accepted compared to maximum price of the day
      selector:
        number:
          min: 0
          max: 100
    trigger_time_minute_ON:
      name: Trigger - Turn ON
      selector:
        number:
          min: 0
          max: 59
    trigger_time_minute_OFF:
      name: Trigger - Turn OFF
      selector:
        number:
          min: 0
          max: 59
    condition_time_after_weekdays:
      name: Condition - After (Weekdays)
      selector:
        time:
    condition_time_after_weekends:
      name: Condition - After (Weekends)
      selector:
        time:
    condition_time_before:
      name: Condition - Before
      selector:
        time:
    heater_devide_id:
      name: Heater Device
      selector:
        device:
    heater_devide_switch:
      name: Heater Switch Entity
      selector:
        entity:
          domain: switch

mode: single
max_exceeded: silent
variables:
  energy_sensor: !input "energy_sensor"
  accepted_percentage: !input accepted_percentage
  energy_sensor_state: "{{ float(states[energy_sensor].state)}}"
  energy_sensor_max: "{{ float(states[energy_sensor].attributes['max_price']) }}"
  is_price_acceptable: "{{ energy_sensor_state <= (energy_sensor_max * (accepted_percentage / 100)) }}"
  var_trigger_time_minute_ON: !input trigger_time_minute_ON
  var_trigger_time_minute_OFF: !input trigger_time_minute_OFF
trigger:
  - platform: time_pattern
    minutes: !input trigger_time_minute_ON
  - platform: time_pattern
    minutes: !input trigger_time_minute_OFF
condition:
  - condition: time
    before: !input condition_time_before
    after: !input condition_time_after_weekdays
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: time
    before: !input condition_time_before
    after: !input condition_time_after_weekends
    weekday:
      - sat
      - sun
  - condition: template
    value_template: "{{ var_trigger_time_minute_ON != var_trigger_time_minute_OFF }}"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ now().minute == var_trigger_time_minute_ON }}"
          - condition: template
            value_template: "{{ is_price_acceptable == true }}"
          - condition: state
            entity_id: input_boolean.am_i_home
            state: "on"
        sequence:
          - type: turn_on
            device_id: !input heater_devide_id
            entity_id: !input heater_devide_switch
            domain: switch
      - conditions:
          - condition: template
            value_template: "{{ now().minute == var_trigger_time_minute_OFF }}"
        sequence:
          - type: turn_off
            device_id: !input heater_devide_id
            entity_id: !input heater_devide_switch
            domain: switch
    default: []
