blueprint:
  name: "Toggles Rules"
  description: ""
  domain: automation
  input:
    anybody_home:
      name: "Is anybody home?"
      selector:
        entity:
          domain: input_boolean
      default: "input_boolean.is_anybody_home"
    anybody_guest_room:
      name: "Is there anyone in the guest room?"
      selector:
        entity:
          domain: input_boolean
      default: "input_boolean.is_there_anyone_in_the_guest_room"
    anybody_common_area:
      name: "Is there anyone in the common area?"
      selector:
        entity:
          domain: input_boolean
      default: "input_boolean.is_there_anyone_in_the_common_area"
    anybody_bedroom:
      name: "Is there anyone in the bedroom?"
      selector:
        entity:
          domain: input_boolean
      default: "input_boolean.is_there_anyone_in_the_bedroom"
    still_watching:
      name: "Still watching?"
      selector:
        entity:
          domain: input_boolean
      default: "input_boolean.still_watching"
    bedroom_socket_device_id:
      name: "Bedroom Socket"
      selector:
        device:
    bedroom_socket_device_switch:
      name: "Bedroom Socket - Switch Entity"
      selector:
        entity:
          domain: switch
    living_room_heater_device_id:
      name: "Living Room Heater"
      selector:
        device:
    living_room_heater_device_switch:
      name: "Living Room Heater - Switch Entity"
      selector:
        entity:
          domain: switch
    dining_room_heater_device_id:
      name: "Dining Room Heater"
      selector:
        device:
    dining_room_heater_device_switch:
      name: "Dining Room Heater - Switch Entity"
      selector:
        entity:
          domain: switch
    guest_room_heater_device_id:
      name: "Guest Room Heater"
      selector:
        device:
    guest_room_heater_device_switch:
      name: "Guest Room Heater - Switch Entity"
      selector:
        entity:
          domain: switch
trigger:
  - platform: state
    entity_id: !input anybody_home
    id: Trigger_Check_Is_Anybody_Home
  - platform: state
    entity_id: !input anybody_bedroom
    id: Trigger_Check_Is_Anybody_Bedroom
  - platform: state
    entity_id: !input anybody_common_area
    id: Trigger_Check_Is_Anybody_Common_Area
  - platform: state
    entity_id: !input anybody_guest_room
    id: Trigger_Check_Is_Anybody_Guest_Room
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Trigger_Check_Is_Anybody_Home
          - condition: state
            entity_id: !input anybody_home
            state: "off"
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - !input anybody_bedroom
                - !input anybody_common_area
                - !input anybody_guest_room
  - choose:
      - conditions:
          - condition: trigger
            id: Trigger_Check_Is_Anybody_Common_Area
          - condition: state
            entity_id: !input anybody_common_area
            state: "on"
        sequence:
          - type: turn_on
            device_id: !input living_room_heater_device_id
            entity_id: !input living_room_heater_device_switch
            domain: switch
      - conditions:
          - condition: trigger
            id: Trigger_Check_Is_Anybody_Common_Area
          - condition: state
            entity_id: !input anybody_common_area
            state: "off"
        sequence:
          - type: turn_off
            device_id: !input living_room_heater_device_id
            entity_id: !input living_room_heater_device_switch
            domain: switch
  - choose:
      - conditions:
          - condition: trigger
            id: Trigger_Check_Is_Anybody_Bedroom
          - condition: state
            entity_id: !input anybody_bedroom
            state: "on"
        sequence:
          - type: turn_on
            device_id: !input bedroom_socket_device_id
            entity_id: !input bedroom_socket_device_switch
            domain: switch
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id:
                - !input still_watching
      - conditions:
          - condition: trigger
            id: Trigger_Check_Is_Anybody_Bedroom
          - condition: state
            entity_id: !input anybody_bedroom
            state: "off"
        sequence:
          - type: turn_off
            device_id: !input bedroom_socket_device_id
            entity_id: !input bedroom_socket_device_switch
            domain: switch
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - !input still_watching
mode: single
max_exceeded: silent
